name: Deploy Azure Functions (Backend)

on:
  push:
    branches:
      - main # Trigger on push to the main branch
    paths:
      - 'backend/**' # Only trigger if changes are in the 'backend' directory

env:
  AZURE_FUNCTIONAPP_NAME: transcriber-func # <--- REPLACE with your Function App name
  PYTHON_VERSION: '3.10' # Must match your Function App runtime version
  FUNCTION_APP_CODE_PATH: 'backend/Host' # Path to your Function App code within the repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Python Version'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install backend dependencies'
        run: |
          python -m pip install --upgrade pip
          # IMPORTANT: requirements.txt is in 'backend/' directory, not 'backend/Host/'
          pip install -r backend/requirements.txt

      - name: 'Zip Function App content'
        run: |
          # Change directory to where the actual function app code is located
          # and then zip its contents.
          cd ${{ env.FUNCTION_APP_CODE_PATH }}
          zip -r ../../functionapp.zip .
          cd ../.. # Go back to the root of the repository

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          # This secret holds the Azure Service Principal credentials
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Azure Function App'
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './functionapp.zip' # Path to the zipped package relative to the repo root

      - name: 'Logout from Azure'
        run: az logout
